-- begin TEZISCONTROLWORK_CAR
alter table TEZISCONTROLWORK_CAR add constraint FK_TEZISCONTROLWORK_CAR_CAR_BRAND_ID foreign key (CAR_BRAND_ID) references TEZISCONTROLWORK_CAR_BRAND(ID)^
alter table TEZISCONTROLWORK_CAR add constraint FK_TEZISCONTROLWORK_CAR_CARD_ID foreign key (CARD_ID) references WF_CARD(ID)^
create index IDX_TEZISCONTROLWORK_CAR_CAR_BRAND on TEZISCONTROLWORK_CAR (CAR_BRAND_ID)^
-- end TEZISCONTROLWORK_CAR
-- begin TEZISCONTROLWORK_ORDER_BUY_CAR
alter table TEZISCONTROLWORK_ORDER_BUY_CAR add constraint FK_TEZISCONTROLWORK_ORDER_BUY_CAR_CAR_ID foreign key (CAR_ID) references TEZISCONTROLWORK_CAR(CARD_ID)^
alter table TEZISCONTROLWORK_ORDER_BUY_CAR add constraint FK_TEZISCONTROLWORK_ORDER_BUY_CAR_CONTRACTOR_ID foreign key (CONTRACTOR_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table TEZISCONTROLWORK_ORDER_BUY_CAR add constraint FK_TEZISCONTROLWORK_ORDER_BUY_CAR_BANK_ID foreign key (BANK_ID) references DF_BANK(ID)^
alter table TEZISCONTROLWORK_ORDER_BUY_CAR add constraint FK_TEZISCONTROLWORK_ORDER_BUY_CAR_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_TEZISCONTROLWORK_ORDER_BUY_CAR_CONTRACTOR on TEZISCONTROLWORK_ORDER_BUY_CAR (CONTRACTOR_ID)^
create index IDX_TEZISCONTROLWORK_ORDER_BUY_CAR_CAR on TEZISCONTROLWORK_ORDER_BUY_CAR (CAR_ID)^
create index IDX_TEZISCONTROLWORK_ORDER_BUY_CAR_BANK on TEZISCONTROLWORK_ORDER_BUY_CAR (BANK_ID)^
-- end TEZISCONTROLWORK_ORDER_BUY_CAR
