-- begin TEZISCONTROLWORK_CAR
alter table TEZISCONTROLWORK_CAR add constraint FK_TEZISCONTROLWORK_CAR_CAR_BRAND_ID foreign key (CAR_BRAND_ID) references TEZISCONTROLWORK_CAR_BRAND(ID)^
alter table TEZISCONTROLWORK_CAR add constraint FK_TEZISCONTROLWORK_CAR_CARD_ID foreign key (CARD_ID) references WF_CARD(ID)^
create index IDX_TEZISCONTROLWORK_CAR_CAR_BRAND on TEZISCONTROLWORK_CAR (CAR_BRAND_ID)^
-- end TEZISCONTROLWORK_CAR
